// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
namespace RehabTracking.Web.Resources {
    using System;
    
    public class ErrorMessages {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ErrorMessages() { }
        
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RehabTracking.Web.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        public static string DataProcessingFailed {
            get {
                return ResourceManager.GetString("DataProcessingFailed", resourceCulture);
            }
        }
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        public static string InvalidTargetRepetitions {
            get {
                return ResourceManager.GetString("InvalidTargetRepetitions", resourceCulture);
            }
        }
        public static string InvalidTargetDuration {
            get {
                return ResourceManager.GetString("InvalidTargetDuration", resourceCulture);
            }
        }
        public static string InvalidAvgEmg {
            get {
                return ResourceManager.GetString("InvalidAvgEmg", resourceCulture);
            }
        }
        public static string InvalidMaxRom {
            get {
                return ResourceManager.GetString("InvalidMaxRom", resourceCulture);
            }
        }
        public static string PositiveRepetitions {
            get {
                return ResourceManager.GetString("PositiveRepetitions", resourceCulture);
            }
        }
        public static string InvalidDurationMinutes {
            get {
                return ResourceManager.GetString("InvalidDurationMinutes", resourceCulture);
            }
        }
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        public static string DeviceAlreadyActivated {
            get {
                return ResourceManager.GetString("DeviceAlreadyActivated", resourceCulture);
            }
        }
        public static string DoctorRoleNotFound {
            get {
                return ResourceManager.GetString("DoctorRoleNotFound", resourceCulture);
            }
        }
        public static string NoDoctorAvailable {
            get {
                return ResourceManager.GetString("NoDoctorAvailable", resourceCulture);
            }
        }
        public static string UserAuthenticationError {
            get {
                return ResourceManager.GetString("UserAuthenticationError", resourceCulture);
            }
        }
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
