// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
namespace RehabTracking.Web.Resources {
    using System;
    
    public class Messages {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public Messages() { }
        
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RehabTracking.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        public static string DataReceivedSuccess {
            get {
                return ResourceManager.GetString("DataReceivedSuccess", resourceCulture);
            }
        }
        public static string DeviceActivationSuccess {
            get {
                return ResourceManager.GetString("DeviceActivationSuccess", resourceCulture);
            }
        }
    }
}
